export enum FailureCategory {
    LOCATOR_FAILURE = "LOCATOR_FAILURE",

    ASSERTION_FAILURE = "ASSERTION_FAILURE",

    AUTH_FAILURE = "AUTH_FAILURE",

    API_FAILURE = "API_FAILURE",

    NETWORK_FAILURE = "NETWORK_FAILURE",

    TEST_DATA_FAILURE = "TEST_DATA_FAILURE",

    ENVIRONMENT_FAILURE = "ENVIRONMENT_FAILURE",

    TIMEOUT_FAILURE = "TIMEOUT_FAILURE",

    UNKNOWN_FAILURE = "UNKNOWN_FAILURE"
}